logging:
  config: classpath:logback/logback-spring.xml

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: None
        http-only: true

spring:
  config:
    import:
      - classpath:logging.yml
      - classpath:monitoring.yml
      - classpath:storage.yml
  application:
    name: veri-be
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  swagger-ui:
    path: /resources/docs/swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /resources/docs/v3/api-docs

auth:
  jwt:
    use: true
  oauth2:
    dynamic-redirect: true

jwt:
  access:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
    validity: 3600000 # 1 hour
  refresh:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
    validity: 2592000000 # 30 days
