spring:
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /resources/docs/swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /resources/docs/v3/api-docs

logging:
  level:
    root: info
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: TRACE
#    org.apache.http.wire: DEBUG

auth:
  jwt:
    use: true
  oauth2:
    dynamic-redirect: true
